URL_SERVICE = "https://c6b3e844-cc16-4fd0-b77e-54dfb001fc6d.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/" 
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/" 
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"